import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'Salesforce developer (2 years exp)',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: '',
  },
  {
    id: 2,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'Salesforce developer (3 -5  years exp)',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: '',
  },
  {
    id: 3,
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'Salesforce developer (5+)',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: '',
  },
  {
    id: 4,
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'Lead Developer',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: '',
  },
  {
    id: 5,
    cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
    title: 'Salesforce architect',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: '',
  },
  {
    id: 6,
    cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
    title: 'Vlocity developer',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: '',
  },
  {
    id: 7,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Omnistudio developer',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: '',
  },
  {
    id: 8,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Salesforce tester',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: '',
  },
]
